#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# get app
APP="$1"

# log
echo "-----> post-deploy for spamassassin"

#sudo
#sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/spamassassin

echo "test" >> /app/log.txt

# reload config
#sudo
#/etc/init.d/spamassassin restart
