#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# get app
APP="$1"

# check if there is a PORTS file
if [ -f $DOKKU_ROOT/$APP/PORTS ]; then
  # log
  echo "-----> post-deploy for spamassassin"

  # reload config
  sudo /etc/init.d/spamassassin restart
fi
