#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

SCRIPT=$(cat <<EOF
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/spamassassin
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
echo '-----> setup spamassassin'
id=$(echo "$SCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.spamassassin")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.spamassassin")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo '-----> /setup spamassassin'
